import { slugify } from "../slug";

/**
 * Canonical identity for clubs. Providers spell names differently; we key by a
 * normalised form and by an alias table. Anything that still does not match is
 * a candidate for the AI matcher, never a silent new team.
 */
const STOP = new Set([
  "fc",
  "cf",
  "afc",
  "ac",
  "as",
  "ss",
  "sc",
  "us",
  "ssc",
  "acf",
  "rcd",
  "ud",
  "ca",
  "sv",
  "vfl",
  "vfb",
  "tsg",
  "fsv",
  "bsc",
  "sk",
  "fk",
  "gnk",
  "krc",
  "losc",
  "ogc",
  "rb",
  "the",
  "de",
  "club",
  "calcio",
  "1909",
  "1913",
  "1907",
  "04",
  "05",
  "1",
  "1899",
  "bc",
  "cfc",
  "sl",
  "cp",
  "psv",
  "sg",
]);

export function normalizeName(name: string): string {
  return slugify(name)
    .split("-")
    .filter((tok) => tok && !STOP.has(tok))
    .join(" ")
    .trim();
}

/** Hand-curated aliases: normalised provider name -> our team id. Extend as providers are added. */
export const TEAM_ALIASES: Record<string, string> = {
  "manchester united": "manchester-united",
  "man united": "manchester-united",
  "man utd": "manchester-united",
  "manchester city": "manchester-city",
  "man city": "manchester-city",
  "tottenham hotspur": "tottenham-hotspur",
  tottenham: "tottenham-hotspur",
  spurs: "tottenham-hotspur",
  "wolverhampton wanderers": "wolverhampton-wanderers",
  wolves: "wolverhampton-wanderers",
  "newcastle united": "newcastle-united",
  newcastle: "newcastle-united",
  "brighton hove albion": "brighton",
  "brighton and hove albion": "brighton",
  brighton: "brighton",
  "west ham united": "west-ham-united",
  "west ham": "west-ham-united",
  "nottingham forest": "nottingham-forest",
  "nottm forest": "nottingham-forest",
  bournemouth: "bournemouth",
  "leeds united": "leeds-united",
  "crystal palace": "crystal-palace",
  "aston villa": "aston-villa",
  "atletico madrid": "atletico-madrid",
  "atletico de madrid": "atletico-madrid",
  "real madrid": "real-madrid",
  barcelona: "barcelona",
  "athletic club": "athletic-club",
  "athletic bilbao": "athletic-club",
  "real betis": "real-betis",
  "real betis balompie": "real-betis",
  "celta vigo": "celta-vigo",
  "celta de vigo": "celta-vigo",
  "real sociedad": "real-sociedad",
  "real sociedad de futbol": "real-sociedad",
  "rayo vallecano": "rayo-vallecano",
  "rayo vallecano de madrid": "rayo-vallecano",
  "deportivo alaves": "alaves",
  alaves: "alaves",
  "real oviedo": "real-oviedo",
  villarreal: "villarreal",
  sevilla: "sevilla",
  valencia: "valencia",
  getafe: "getafe",
  girona: "girona",
  mallorca: "mallorca",
  osasuna: "osasuna",
  espanyol: "espanyol",
  "espanyol de barcelona": "espanyol",
  levante: "levante",
  elche: "elche",
  "bayern munchen": "bayern-munich",
  "bayern munich": "bayern-munich",
  bayern: "bayern-munich",
  "borussia dortmund": "borussia-dortmund",
  dortmund: "borussia-dortmund",
  "bayer leverkusen": "bayer-leverkusen",
  leverkusen: "bayer-leverkusen",
  "borussia monchengladbach": "borussia-monchengladbach",
  monchengladbach: "borussia-monchengladbach",
  gladbach: "borussia-monchengladbach",
  "eintracht frankfurt": "eintracht-frankfurt",
  frankfurt: "eintracht-frankfurt",
  koln: "fc-koln",
  cologne: "fc-koln",
  "hamburger sv": "hamburger-sv",
  hamburg: "hamburger-sv",
  heidenheim: "heidenheim",
  hoffenheim: "hoffenheim",
  "mainz 05": "mainz-05",
  mainz: "mainz-05",
  leipzig: "rb-leipzig",
  "rb leipzig": "rb-leipzig",
  freiburg: "sc-freiburg",
  "st pauli": "st-pauli",
  stuttgart: "vfb-stuttgart",
  "union berlin": "union-berlin",
  "werder bremen": "werder-bremen",
  wolfsburg: "vfl-wolfsburg",
  augsburg: "augsburg",
  inter: "inter",
  "inter milan": "inter",
  internazionale: "inter",
  "fc internazionale milano": "inter",
  milan: "milan",
  "ac milan": "milan",
  juventus: "juventus",
  napoli: "napoli",
  roma: "roma",
  lazio: "lazio",
  atalanta: "atalanta",
  bologna: "bologna",
  fiorentina: "fiorentina",
  torino: "torino",
  udinese: "udinese",
  genoa: "genoa",
  cagliari: "cagliari",
  parma: "parma",
  sassuolo: "sassuolo",
  lecce: "lecce",
  "hellas verona": "hellas-verona",
  verona: "hellas-verona",
  como: "como",
  cremonese: "cremonese",
  pisa: "pisa",
  "paris saint germain": "psg",
  psg: "psg",
  "paris sg": "psg",
  "olympique de marseille": "marseille",
  "olympique marseille": "marseille",
  marseille: "marseille",
  monaco: "monaco",
  lille: "lille",
  "olympique lyonnais": "lyon",
  lyon: "lyon",
  nice: "nice",
  benfica: "benfica",
  "sporting cp": "sporting-cp",
  "sporting lisbon": "sporting-cp",
  sporting: "sporting-cp",
  porto: "porto",
  braga: "braga",
  ajax: "ajax",
  eindhoven: "psv",
  feyenoord: "feyenoord",
  utrecht: "utrecht",
  "go ahead eagles": "go-ahead-eagles",
  "club brugge": "club-brugge",
  "club brugge kv": "club-brugge",
  "union saint gilloise": "union-sg",
  "royale union saint gilloise": "union-sg",
  "union sg": "union-sg",
  genk: "genk",
  celtic: "celtic",
  rangers: "rangers",
  galatasaray: "galatasaray",
  fenerbahce: "fenerbahce",
  olympiacos: "olympiacos",
  "olympiacos piraeus": "olympiacos",
  paok: "paok",
  panathinaikos: "panathinaikos",
  "slavia praha": "slavia-praha",
  "slavia prague": "slavia-praha",
  "viktoria plzen": "viktoria-plzen",
  "bodo glimt": "bodo-glimt",
  brann: "brann",
  copenhagen: "copenhagen",
  kobenhavn: "copenhagen",
  midtjylland: "midtjylland",
  qarabag: "qarabag",
  pafos: "pafos",
  kairat: "kairat",
  "kairat almaty": "kairat",
  "dinamo zagreb": "dinamo-zagreb",
  "red bull salzburg": "salzburg",
  salzburg: "salzburg",
  "sturm graz": "sturm-graz",
  "crvena zvezda": "crvena-zvezda",
  "red star belgrade": "crvena-zvezda",
  ferencvaros: "ferencvaros",
  "ferencvarosi tc": "ferencvaros",
  "maccabi tel aviv": "maccabi-tel-aviv",
  "young boys": "young-boys",
  basel: "basel",
  ludogorets: "ludogorets",
  "ludogorets razgrad": "ludogorets",
  malmo: "malmo",
  "malmo ff": "malmo",
  fcsb: "fcsb",
  // 2026/27 arrivals and other UEFA regulars (ids chosen before the provider's spelling could mint one)
  "hull city": "hull-city",
  "ipswich town": "ipswich-town",
  "coventry city": "coventry-city",
  malaga: "malaga",
  "deportivo la coruna": "deportivo-la-coruna",
  deportivo: "deportivo-la-coruna",
  "racing santander": "racing-santander",
  "real racing club de santander": "racing-santander",
  santander: "racing-santander",
  "schalke 04": "schalke-04",
  schalke: "schalke-04",
  "paderborn 07": "paderborn",
  paderborn: "paderborn",
  "07 elversberg": "elversberg",
  elversberg: "elversberg",
  venezia: "venezia",
  frosinone: "frosinone",
  monza: "monza",
  "racing club de lens": "lens",
  lens: "lens",
  "shakhtar donetsk": "shakhtar-donetsk",
  shakhtar: "shakhtar-donetsk",
  shaktar: "shakhtar-donetsk",
  "pae aek": "aek-athens",
  "aek athens": "aek-athens",
  aek: "aek-athens",
  "lask linz": "lask",
  lask: "lask",
  "viking fk": "viking",
  viking: "viking",
  "slovan bratislava": "slovan-bratislava",
  "sl bratislava": "slovan-bratislava",
  "sabah fk": "sabah",
  sabah: "sabah",
  // API-Football spellings
  leeds: "leeds-united",
  "psv eindhoven": "psv",
  "union st gilloise": "union-sg",
  "olympiakos piraeus": "olympiacos",
  olympiakos: "olympiacos",
  "basel 1893": "basel",
  "as roma": "roma",
  "fc porto": "porto",
  "fc copenhagen": "copenhagen",
  "fc midtjylland": "midtjylland",
  "bodo/glimt": "bodo-glimt",
  "aek athens fc": "aek-athens",
};

// Alias keys are normalised the same way provider names are, so "FC Internazionale Milano"
// and "internazionale milano" hit the same entry.
const ALIAS_INDEX = new Map(Object.entries(TEAM_ALIASES).map(([k, v]) => [normalizeName(k), v]));

export function resolveTeamId(
  providerName: string,
  known: Iterable<{ id: string; name: string; shortName: string }>,
): string | null {
  const key = normalizeName(providerName);
  const alias = ALIAS_INDEX.get(key);
  if (alias) return alias;
  for (const t of known) {
    if (normalizeName(t.name) === key || normalizeName(t.shortName) === key) return t.id;
  }
  return null;
}

export const COMPETITION_CODES: Record<string, { footballData?: string; apiFootball?: number }> = {
  epl: { footballData: "PL", apiFootball: 39 },
  laliga: { footballData: "PD", apiFootball: 140 },
  bundesliga: { footballData: "BL1", apiFootball: 78 },
  seriea: { footballData: "SA", apiFootball: 135 },
  ligue1: { footballData: "FL1", apiFootball: 61 },
  eredivisie: { footballData: "DED", apiFootball: 88 },
  primeira: { footballData: "PPL", apiFootball: 94 },
  championship: { footballData: "ELC", apiFootball: 40 },
  brasileirao: { footballData: "BSA", apiFootball: 71 },
  ucl: { footballData: "CL", apiFootball: 2 },
  uel: { footballData: "EL", apiFootball: 3 },
};
